name: dart_event_emitter
version: 1.0.1
homepage: https://github.com/eps90/event-emitter.dart
description: Simple EventEmitter implementation in Dart
author: Jakub Turek <ja@kubaturek.pl>
environment:
  sdk: '>=1.20.1 <3.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
