name: event_emitter
version: 1.0.0
homepage: https://github.com/eps90/event-emitter.dart
description: Simple EventEmitter implementation in Dart
author: Jakub Turek <kubus1990@gmail.com>
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
